name: Publish LangChain to npm

on:
  push:
    tags:
      - 'langchain-v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        type: string
      tag:
        description: 'NPM tag (latest, beta, next)'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta
          - next

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd integrations/langchain/typescript
          npm ci
      
      - name: Build package
        run: |
          cd integrations/langchain/typescript
          npm run build
      
      - name: Run tests
        run: |
          cd integrations/langchain/typescript
          npm test
      
      - name: Update version if provided
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd integrations/langchain/typescript
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
      
      - name: Publish to npm
        run: |
          cd integrations/langchain/typescript
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            npm publish --access public --tag ${{ github.event.inputs.tag }}
          else
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: LangChain Integration ${{ github.ref }}
          body: |
            ## SEC EDGAR Agentkit for LangChain
            
            LangChain toolkit for SEC EDGAR data analysis.
            
            ### Installation
            ```bash
            npm install @sec-edgar-agentkit/langchain
            ```
            
            See [README](https://github.com/${{ github.repository }}/tree/main/integrations/langchain) for usage.
          draft: false
          prerelease: false