name: Test MCP-use Integration

on:
  push:
    branches: [main, develop]
    paths:
      - 'integrations/mcp-use/**'
      - '.github/workflows/test-mcp-use.yml'
  pull_request:
    branches: [main]
    paths:
      - 'integrations/mcp-use/**'
      - '.github/workflows/test-mcp-use.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd integrations/mcp-use
          npm ci
      
      - name: Run tests
        run: |
          cd integrations/mcp-use
          npm test
      
      - name: Lint check
        run: |
          cd integrations/mcp-use
          npx eslint . --ext .js || true